using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Client.Viewport;
using Content.Client.UserInterface.Systems.Viewport;
using Robust.Client.Timing;
using Robust.Shared.Graphics;
using Robust.Shared.Timing;
using System.Numerics;

namespace Content.Client._Starlight.Computers.RemoteControl;

[GenerateTypedNameReferences]
public sealed partial class RemoteControlConsoleWindow : FancyWindow
{
    [Dependency] private IEyeManager _eyeManager = default!;

    private readonly Robust.Shared.Graphics.Eye _remoteEye = new();
    private IEye? _sourceEye;
    public event Action? ToggleControl;
    public RemoteControlConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ControlButton.OnPressed += _ => ToggleControl?.Invoke();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_sourceEye == null)
            return;

        _remoteEye.Position = _sourceEye.Position;
        _remoteEye.Offset = _sourceEye.Offset;
        _remoteEye.Zoom = _sourceEye.Zoom;
        _remoteEye.DrawFov = _sourceEye.DrawFov;
        _remoteEye.DrawLight = _sourceEye.DrawLight;
        _remoteEye.Rotation = _sourceEye.Rotation;
    }

    public void InitializeViewport()
    {
        RemoteView.ViewportSize = ViewportUIController.ViewportSize;
        RemoteView.StretchMode = ScalingViewportStretchMode.Bilinear;
        RemoteView.RenderScaleMode = ScalingViewportRenderScaleMode.Fixed;
        RemoteView.FixedRenderScale = 1;
        RemoteView.OnResized += OnViewportResized;
        OnViewportResized();
    }

    public void SetConnected(bool connected)
    {
        StatusLabel.Text = connected ? "Remote entity connected" : "No remote entity connected";
        RemoteView.Visible = connected;
        ControlButton.Visible = connected;
    }

    public void SetControlState(bool controlling, bool occupied)
    {
        ControlButton.Text = controlling ? "Release control" : "Take control";
        ControlButton.Disabled = occupied && !controlling;
    }

    public void SetRemoteEye(IEye? eye)
    {
        _sourceEye = eye;
        RemoteView.Eye = eye == null ? null : _remoteEye;
    }

    private void OnViewportResized()
    {
        var width = Math.Max(RemoteView.PixelWidth, (int) Math.Floor(RemoteView.MinWidth));
        var height = Math.Max(RemoteView.PixelHeight, (int) Math.Floor(RemoteView.MinHeight));
        var viewSize = (Vector2) RemoteView.ViewportSize;
        var scale = Math.Min(width / viewSize.X, height / viewSize.Y);
        RemoteView.FixedStretchSize = (Vector2i) (viewSize * scale);
    }
}
